<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nanti Dulu</name>
   <tag></tag>
   <elementGuidId>823055fb-5e33-4f48-892f-cd9dbd6fb671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='moeRemoveBanner()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf67b2f1-bf2d-48ce-b3e1-e70bfb07eabd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>moeRemoveBanner()</value>
      <webElementGuid>6ede5900-350e-493a-8fea-d543c880e781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'color': webPushPreview['bannerv2']['web']['closeButton']['color'],'background':webPushPreview['bannerv2']['web']['closeButton']['backgroundColor']}</value>
      <webElementGuid>d62041b9-65c2-4c78-9474-4b7871445a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>971f1585-9f7d-4788-9b93-4e27e3e31e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nanti Dulu</value>
      <webElementGuid>18076849-7343-48e9-ab6f-766ff07f876f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desktopBannerWrapped&quot;)/div[1]/div[3]/div[1]/button[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>2f0b61e7-f15e-46b0-95b8-dbd33412c4f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='moeRemoveBanner()']</value>
      <webElementGuid>66288ea8-7680-40b5-8d5d-fba6114aedaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktopBannerWrapped']/div/div[3]/div/button</value>
      <webElementGuid>580e892f-2121-471c-953b-c2dd8bb18fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yuk Jadi Yang Pertama Tau Diskon &amp; Penawaran Terbaik Dari JD.ID'])[1]/following::button[1]</value>
      <webElementGuid>837ff13d-24ce-45d8-94c5-f0515d2600a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktifkan'])[1]/preceding::button[1]</value>
      <webElementGuid>501b46ee-20a1-4cbd-bbec-f6d0fee45dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::button[2]</value>
      <webElementGuid>4714d68e-d3fe-431e-adc8-164a06dd8f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nanti Dulu']/parent::*</value>
      <webElementGuid>34ab6571-b275-44ab-ae3e-2cc5fe2debd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b6ec0f42-67c3-45af-b072-0ac5d6bf527e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Nanti Dulu' or . = 'Nanti Dulu')]</value>
      <webElementGuid>35c7cf70-b12c-490e-9d97-2c8542207811</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
