<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Beranda</name>
   <tag></tag>
   <elementGuidId>4d8aeea1-8bfa-4ed1-ba66-5f52d3c94570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.mt34.button-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/div[5]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cfdcbe37-eccc-470a-9a28-47ce298c009a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>//www.jd.id/</value>
      <webElementGuid>f28a2f41-4522-44dc-9813-c59158dfd534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button mt34 button-active</value>
      <webElementGuid>6509b3c5-46b5-4348-b5a4-b373f5d7eed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beranda</value>
      <webElementGuid>f570edff-6571-4dcd-8c0e-0150e0e53a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;confirmation&quot;]/div[@class=&quot;confirmation-content&quot;]/div[5]/div[1]/a[@class=&quot;button mt34 button-active&quot;]</value>
      <webElementGuid>580a58dd-459a-4110-8f6a-69ebda79bb08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div[5]/div/a</value>
      <webElementGuid>292c9f31-9e7f-4b01-9037-a6b32498bf48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Beranda')]</value>
      <webElementGuid>e7fc04fe-8113-4106-a5d2-207f1596651e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periksa kembali kode tagihan sesuai dengan yang tertera di atas sebelum melakukan pembayaran'])[1]/following::a[1]</value>
      <webElementGuid>0614957a-52da-4fe5-ab85-411b94428538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satu Nomor Virtual Account Hanya Diperuntukan Untuk Satu Order ID'])[1]/following::a[1]</value>
      <webElementGuid>4bc9a773-5338-4900-bdff-3316d3941f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan Saya'])[2]/preceding::a[1]</value>
      <webElementGuid>8b9845b4-71ce-4efe-bc4c-164177c60386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salin'])[1]/preceding::a[2]</value>
      <webElementGuid>93537ff1-bfc4-4617-b148-6ec6c1f5a3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beranda']/parent::*</value>
      <webElementGuid>aef9e521-122e-48b4-aa3b-2de079bcd1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '//www.jd.id/')])[2]</value>
      <webElementGuid>8e035482-1b87-4f65-9673-38d0e7df6d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>2cad9d8a-8ae2-48e4-ba57-2b3eee538ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '//www.jd.id/' and (text() = 'Beranda' or . = 'Beranda')]</value>
      <webElementGuid>07f1af15-b975-4d15-bf10-3e44ef303f16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
