<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>e17c4e00-7c99-4da0-be00-4d63a9511bf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ccc6142-bc8f-4d8c-872d-34460aac5619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5eaab66f-83b6-4e66-ab61-c73f15aca789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>db8ee64b-94fc-4c94-aeca-c500be0950d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-cart-wrapper&quot;)/section[@class=&quot;bl-section&quot;]/div[@class=&quot;bl-container&quot;]/div[@class=&quot;bl-flex-container justify-center is-gutter-24&quot;]/div[@class=&quot;bl-flex-item is-col-8&quot;]/div[@class=&quot;p-20  mb-16 bl-card bl-card--outlined&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item is-col-6&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item&quot;]/label[@class=&quot;bl-checkbox qa-bulk-checkbox&quot;]/input[1]</value>
      <webElementGuid>06616b5c-0675-44b4-ae69-284ba5a934d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='true']</value>
      <webElementGuid>9e891d13-e44d-4a8e-aa2b-0a0b4d143a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-cart-wrapper']/section[2]/div/div/div/div/div/div/div/div/label/input</value>
      <webElementGuid>d1368242-c836-4829-b800-a8b2626040be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>6292cc68-95c7-4db2-ac26-8329d63acbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>73934acd-4e8f-43f7-b749-f92f76b8190e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
