<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nanti Saja</name>
   <tag></tag>
   <elementGuidId>ba64d6de-dbc1-4064-b65c-41a7cd6d4e9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal']/div[2]/div/div/div/div/div/div/div/div/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.cancel-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d0cc72b-c25d-4d57-9358-1f8383c503aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cancel-btn</value>
      <webElementGuid>ad1dff1a-655c-4868-93c0-9c595ee589e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nanti Saja</value>
      <webElementGuid>09ede33a-0aba-4787-b60c-6ab4de7233c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal&quot;)/div[@class=&quot;stardust-popup&quot;]/div[@class=&quot;stardust-popup__dialog--wrapper&quot;]/div[@class=&quot;stardust-popup__dialog&quot;]/div[@class=&quot;stardust-popup__dialog--wrapper-top&quot;]/div[@class=&quot;stardust-popup-content&quot;]/div[@class=&quot;FN5VY6&quot;]/div[1]/div[1]/div[@class=&quot;shopee-popup-form AiQAFL&quot;]/div[@class=&quot;shopee-popup-form__footer&quot;]/button[@class=&quot;cancel-btn&quot;]</value>
      <webElementGuid>f73f8526-87d2-4d2b-b01c-4258b4391db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal']/div[2]/div/div/div/div/div/div/div/div/div[3]/button</value>
      <webElementGuid>b6e644a7-7511-4c32-b6ec-22a338e4742b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voucher tidak dapat digunakan di perangkat ini.'])[25]/following::button[1]</value>
      <webElementGuid>df61e389-3f47-43b6-99e6-512bfaa76611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::button[1]</value>
      <webElementGuid>e32801fb-85fe-4b37-8516-041117194214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mmmmmmmmmmlli'])[1]/preceding::button[2]</value>
      <webElementGuid>2b9e1e9d-dd30-42c5-8b18-344a20feee8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nanti Saja']/parent::*</value>
      <webElementGuid>96ce6440-3c38-4d69-a1c7-16bbc559d8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>f8966ecf-7571-4571-ae14-da00fa4506b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Nanti Saja' or . = 'Nanti Saja')]</value>
      <webElementGuid>4c739232-519d-4c75-84db-8445a9cfe8a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
