<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Geser untuk melengkapi puzzle_JDJRV-sli_0242af</name>
   <tag></tag>
   <elementGuidId>fa3c25a6-01f4-4a5e-8068-15f94d30ebfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='JDJRV-wrap-commonBtn']/div[2]/div/div[2]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.JDJRV-slide-inner.JDJRV-slide-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>630d907a-4a2d-456d-8efa-c940e923e7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>JDJRV-slide-inner JDJRV-slide-btn</value>
      <webElementGuid>a76a7576-6f42-4af5-9177-6ffe8ba443fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JDJRV-wrap-commonBtn&quot;)/div[@class=&quot;JDJRV-pop-content&quot;]/div[@class=&quot;JDJRV-slide JDJRV-joybuy&quot;]/div[@class=&quot;JDJRV-slide-bg&quot;]/div[@class=&quot;JDJRV-slide-inner JDJRV-slide-btn&quot;]</value>
      <webElementGuid>58748f6b-bc59-4cd7-8334-f2faa7cbce9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JDJRV-wrap-commonBtn']/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>78faba2b-0f76-47b6-af84-7a0e4e7f44a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geser untuk melengkapi puzzle.'])[1]/following::div[6]</value>
      <webElementGuid>273668b8-d1b9-4f09-b1f1-5bbc5118db23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::div[14]</value>
      <webElementGuid>0bec3a4b-95e5-451e-82b7-98b023174e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>e5ee5be5-a92f-4286-ba5c-aebc3ad316dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
