<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>s_Ambil Segera_close</name>
   <tag></tag>
   <elementGuidId>87ee07ac-794e-4d53-b6d8-792783bc5366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='common-floor-app']/div/div[2]/s</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>s.close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>c470362c-ab84-4dfa-b16e-94d9084bef7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clstag</name>
      <type>Main</type>
      <value>pageclick|keycount|epi_home_membergift|close</value>
      <webElementGuid>af72e2bd-e8e0-4d14-a6ba-6a3680791eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>56a413cf-cca7-4417-9f64-ae1e36208e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;common-floor-app&quot;)/div[@class=&quot;rich-member-gift&quot;]/div[@class=&quot;gift&quot;]/s[@class=&quot;close&quot;]</value>
      <webElementGuid>ead9c6dc-2810-45af-8820-bc6a9067b6e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='common-floor-app']/div/div[2]/s</value>
      <webElementGuid>fb92fa39-174d-4057-8e5d-7d4237939d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/s</value>
      <webElementGuid>238093d7-8a8b-4a9d-ab1a-00346cf99475</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
