<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SMS_off</name>
   <tag></tag>
   <elementGuidId>0db13f9c-acfc-4038-a1ea-107093631578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inputPassportPanel']/div/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.off</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd1e39f5-40b8-4048-b84b-b8f5dda908d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8b7f392b-eae9-4651-a6c0-a6a2c0d89c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputPassportPanel&quot;)/div[@class=&quot;inputPanel mt30&quot;]/span[@class=&quot;off&quot;]</value>
      <webElementGuid>50b811d0-18d5-45ef-a908-b4b2bbf17a87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inputPassportPanel']/div/span[3]</value>
      <webElementGuid>aca1b266-68bf-41e4-8a3a-28375e2588c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>4ede69aa-47af-40b2-aaac-d8c2edfb33ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
