<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Whatsapp</name>
   <tag></tag>
   <elementGuidId>907318fd-6dac-4c5b-9c47-fe0a920637ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.bl-text.bl-text--bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-with-otp-wa']/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b482f720-afb1-4da3-8cd8-3bd69dc56746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-text bl-text--bold</value>
      <webElementGuid>40d74135-b65d-4a13-9d1d-0ff4e4c8f8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Whatsapp</value>
      <webElementGuid>23285f0c-bbae-4b6f-a1a4-5b1be3753b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-with-otp-wa&quot;)/div[@class=&quot;bl-flex-item&quot;]/div[1]/p[@class=&quot;bl-text bl-text--bold&quot;]</value>
      <webElementGuid>5e24321b-912f-47f2-bcfc-0927c31f588e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-with-otp-wa']/div[2]/div/p</value>
      <webElementGuid>afc93b2f-e9b7-41a5-afab-23674d470b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/following::p[4]</value>
      <webElementGuid>8f9bfed5-796a-4f5c-bb9b-f4f420d30c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::p[8]</value>
      <webElementGuid>ce5541ff-0258-4f55-85d4-2d22c2aa25f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*****-****-1016'])[1]/preceding::p[1]</value>
      <webElementGuid>840bed74-8a20-4043-99a6-f8b57df6d46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Whatsapp']/parent::*</value>
      <webElementGuid>6bc6b130-5118-46ff-bf4a-23f7727c2fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/p</value>
      <webElementGuid>2cc5b6cb-43a2-4789-bb10-3edb4f5e0cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Whatsapp' or . = 'Whatsapp')]</value>
      <webElementGuid>7225c490-edde-4ba9-9616-84f01a7d8bc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
