<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>shopee-banner-popup-stateful</name>
   <tag></tag>
   <elementGuidId>9919be38-b479-44aa-a3ca-46a08965bf95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>shopee-banner-popup-stateful</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/shopee-banner-popup-stateful</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>shopee-banner-popup-stateful</value>
      <webElementGuid>db0fd01c-def1-4a0e-b6be-5952f5e4686c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spacekey</name>
      <type>Main</type>
      <value>PC-ID-HOME_POPUP_01</value>
      <webElementGuid>c5e57430-efc3-4217-932c-467801d6456e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;xCao3k N2AB73&quot;]/div[@class=&quot;home-page&quot;]/shopee-banner-popup-stateful[1]</value>
      <webElementGuid>134f85ae-e513-4607-b770-d349c04540b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/shopee-banner-popup-stateful</value>
      <webElementGuid>fc2fd01d-84c6-4fb3-8c27-345cb4648878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//shopee-banner-popup-stateful</value>
      <webElementGuid>e78fa4dc-f01e-4ddc-baa7-70a23aff56b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
