<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bayar</name>
   <tag></tag>
   <elementGuidId>e1789d48-3bf9-40cb-98b5-d60b19c73179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout']/div/div/div/div[5]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.in-b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b99800ea-3ad0-4cdc-b39e-c0021bf334a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clstag</name>
      <type>Main</type>
      <value>pageclick|keycount|epi_confirm_submitOrder|0</value>
      <webElementGuid>854a9f11-301a-4328-a151-b9d981ab878d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>in-b</value>
      <webElementGuid>fc6b6450-3273-4cb2-b0b9-6002334b734a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>501e27ee-ea7b-43ba-9ae3-c8304d4b0656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bayar</value>
      <webElementGuid>43fddf5d-42b9-4ee3-89a9-472fc6d36767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout&quot;)/div[@class=&quot;cart-settlement-root&quot;]/div[@class=&quot;cart-settlement-wrapper cart-settlement-wrapper-fixed&quot;]/div[@class=&quot;cart-settlement cart-settlement-top&quot;]/div[@class=&quot;buy-all&quot;]/div[@class=&quot;buy-all-ctrl&quot;]/a[@class=&quot;in-b&quot;]</value>
      <webElementGuid>682fd18d-2d54-47ad-96ee-8eb563ccc631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout']/div/div/div/div[5]/div[2]/a</value>
      <webElementGuid>d9512505-407f-4aed-93c2-9dd259d8aafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Bayar')])[2]</value>
      <webElementGuid>eeb13ae4-fa7a-4f05-9344-06f18cae643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 659,000'])[1]/following::a[1]</value>
      <webElementGuid>eadc2a94-c4a8-4f64-ae33-4adb5c64acc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Tagihan:'])[1]/following::a[1]</value>
      <webElementGuid>0e733483-38a7-4ef3-bbea-19a94ee513c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Pengiriman'])[1]/preceding::a[1]</value>
      <webElementGuid>ed86f6af-0a01-4493-9cad-7e69920cbf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bayar']/parent::*</value>
      <webElementGuid>2debef87-d8e8-4bd2-8249-3fb81dd93478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[3]</value>
      <webElementGuid>ade3ecea-93eb-4e36-a54f-bc5ef3ab767a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/a</value>
      <webElementGuid>3e3f2314-8942-4b92-9f01-2011e681a12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Bayar' or . = 'Bayar')]</value>
      <webElementGuid>af458146-535d-49ea-8a23-b38beeb39cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
