<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masuk_Password</name>
   <tag></tag>
   <elementGuidId>19c99f1b-d221-4e69-a8f9-dda14e370bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1f87de9-f6c9-4f04-b4f1-b8f810b0f7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3ee4b6d7-663d-4213-9686-d970e89cb191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>1f828bcb-c107-47ae-a97e-e9329a94d8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7e708849-d427-4a20-8cb4-bff4c7079c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>26ec2426-635b-4adf-9e9c-a3518ffdbcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kata Sandi</value>
      <webElementGuid>2f70bbcd-15ec-4848-b166-c953e3d5bcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Z</value>
      <webElementGuid>b3f74af3-e8cb-4b63-b1fc-f87b8055c83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;wrp-content&quot;]/div[@class=&quot;box-border&quot;]/div[@class=&quot;vmiddle&quot;]/form[1]/div[@class=&quot;wrp-reg-content&quot;]/div[@class=&quot;each-field&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>fed9b539-42b6-4645-8ecb-868f0de23509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Password']</value>
      <webElementGuid>ad0e1110-7e1f-4864-ae37-ac0aa071d3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='site-content']/div/div/div/div/form/div/div[2]/input</value>
      <webElementGuid>180b86db-699c-484d-ae4e-230aad416851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>42de579d-c7f6-4c88-b43f-027d716c5930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Password' and @type = 'password' and @placeholder = 'Kata Sandi']</value>
      <webElementGuid>41eb16a3-f7d9-41dc-88d9-4751523fa47f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
