<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Produk Serupa_stardust-checkbox__box</name>
   <tag></tag>
   <elementGuidId>e93a69a9-4195-4ac4-bad5-17fb554a8401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div[3]/div/div[3]/div[2]/div[4]/div/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._2qN5oG > div._216OLk > div._1GcTXp > div.uUhc_B > label.stardust-checkbox > div.stardust-checkbox__box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0482a48-1bcd-4c32-9dd8-6b13efa6564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stardust-checkbox__box</value>
      <webElementGuid>f48a3123-33a0-40c7-b112-e88671d2720f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;_2LNMKb&quot;]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;_1nft6V&quot;]/div[@class=&quot;aCSbhb&quot;]/div[@class=&quot;_2qN5oG&quot;]/div[@class=&quot;_216OLk&quot;]/div[@class=&quot;_1GcTXp&quot;]/div[@class=&quot;uUhc_B&quot;]/label[@class=&quot;stardust-checkbox&quot;]/div[@class=&quot;stardust-checkbox__box&quot;]</value>
      <webElementGuid>b7abde0f-aeb6-4e94-a4ce-0276861bc05c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div[3]/div/div[3]/div[2]/div[4]/div/div/label/div</value>
      <webElementGuid>75044e65-15fc-4f48-956c-1093c1029bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/label/div</value>
      <webElementGuid>ddd8ebdf-5c96-48ac-9d30-9b147a5b4001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
