<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_checkout</name>
   <tag></tag>
   <elementGuidId>f8630818-dc58-4d37-8b49-5c070e2e6e49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div[3]/div[2]/div[7]/button[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.kcsswk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61b0f223-cc83-4a3c-8230-f397363c4687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kcsswk</value>
      <webElementGuid>f031518f-8d24-4f4e-bb75-a6ca2760b1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>checkout</value>
      <webElementGuid>9b6b38bb-1870-4686-83b8-1f9d0437de9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;_2LNMKb&quot;]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;_2jol0L _3GVi82&quot;]/div[@class=&quot;W2HjBQ zzOmij&quot;]/button[@class=&quot;shopee-button-solid shopee-button-solid--primary&quot;]/span[@class=&quot;kcsswk&quot;]</value>
      <webElementGuid>87dce868-734d-4893-a125-9ca3f2924d7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div[3]/div[2]/div[7]/button[4]/span</value>
      <webElementGuid>9f2292bd-a421-404b-a9d6-ca1935c61263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp722RB'])[1]/following::span[1]</value>
      <webElementGuid>0cdee46a-2c93-4ac7-9c4b-2fc4feb3be05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mmmmmmmmmmlli'])[1]/preceding::span[1]</value>
      <webElementGuid>121c3032-20d4-41d9-bead-5211e0d80882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mmmmmmmmmmlli'])[2]/preceding::span[2]</value>
      <webElementGuid>3636571c-8367-4739-872c-dc8428e3b145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='checkout']/parent::*</value>
      <webElementGuid>c1574fc1-f3b5-4c9d-88bc-b79cf0e317e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/span</value>
      <webElementGuid>0b010979-ebcc-4693-9b89-aba5abb9eb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'checkout' or . = 'checkout')]</value>
      <webElementGuid>16b6a12a-964d-4220-a675-891f6157201c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
