<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bayar Sekarang</name>
   <tag></tag>
   <elementGuidId>8f7a2759-225e-4ffa-ae46-82e856f324ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='payButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbdf4193-57c0-4b38-aa69-2b0c4f15cf4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blue-btn</value>
      <webElementGuid>188874f6-6c8b-400e-93d8-5c2d71e0cb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payButton</value>
      <webElementGuid>b7746d49-f4c8-4bc5-9e64-5966ebaf528a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>702</value>
      <webElementGuid>d07f841d-21ea-4134-9b60-a5d1729d80ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-isintallment</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>edf28f55-6396-4f6f-8dbb-d04ac7b0705b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>BCA Virtual Account</value>
      <webElementGuid>09fa17ee-7290-477a-90d3-37e257a4014f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bayar Sekarang</value>
      <webElementGuid>d9806bb6-fa4b-453d-b432-4205c7e9bad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payButton&quot;)</value>
      <webElementGuid>c2a76e1c-3b0a-468c-aa74-46e0c9598a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Klik Indomaret Login and Checkout Item/Page_Klik Indomaret, Easy  Safe Online Shopping/iframe_OK_paymentCenter</value>
      <webElementGuid>b98205bb-439a-4c33-943b-21f8e329ff84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='payButton']</value>
      <webElementGuid>188d0b87-d1ec-4b9b-80fb-181db7ab666f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div[2]/button</value>
      <webElementGuid>2d96ef11-af6d-4014-b764-abbecfa4316b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCA Virtual Account'])[3]/following::button[1]</value>
      <webElementGuid>b143b22a-3e33-4e5b-938c-5e49d15b92be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo kamu kurang. Tambah alat bayar lainnya'])[1]/preceding::button[1]</value>
      <webElementGuid>0394e072-c290-4b92-ac86-100891bef846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2e4e2583-bdf7-4fcb-a751-9ea8ed2ec565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'payButton' and (text() = 'Bayar Sekarang' or . = 'Bayar Sekarang')]</value>
      <webElementGuid>3e3e0cf7-fb06-4302-abf8-821eb2068a69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
