<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih Opsi Pengiriman</name>
   <tag></tag>
   <elementGuidId>8f1fce97-45ea-4aaa-8b1b-d7e3f297648f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-checkout-step1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-checkout-step1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>abf07ed9-5617-42f1-9e06-277870e20dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buyBtn</value>
      <webElementGuid>3e8580cd-8465-40e8-8055-14839dd7ff45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-checkout-step1</value>
      <webElementGuid>7bed9b29-4e48-47bc-aff0-6036ce43a7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Opsi Pengiriman</value>
      <webElementGuid>f68e45b0-c45d-432b-ba8e-bede01dc506c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-checkout-step1&quot;)</value>
      <webElementGuid>a9f4ec81-264e-4969-9ac7-67549bc85b65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-checkout-step1']</value>
      <webElementGuid>446a7c9e-c037-425c-958e-b2817fd3efe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-summary']/div/div/div/div[2]/button</value>
      <webElementGuid>14c1797d-71ec-4787-8252-82a38b0018fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[2]/following::button[1]</value>
      <webElementGuid>1ca4b46d-791a-4614-9c1c-7c86d7aedbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voucher &amp; Promo'])[1]/following::button[1]</value>
      <webElementGuid>109b5b80-c54f-47d3-85de-9c9c0f162204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perbarui Keranjang'])[1]/preceding::button[1]</value>
      <webElementGuid>ad517a90-844c-4e77-8ddf-0423dac944d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar'])[1]/preceding::button[2]</value>
      <webElementGuid>e6b0551f-baec-4d98-8c25-4513515cadac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Opsi Pengiriman']/parent::*</value>
      <webElementGuid>47c63a37-af55-42c2-8ea8-b2f14d42a03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/button</value>
      <webElementGuid>90ba8b51-9260-42a7-aab7-fe0110417117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-checkout-step1' and (text() = 'Pilih Opsi Pengiriman' or . = 'Pilih Opsi Pengiriman')]</value>
      <webElementGuid>e199eaca-e5b6-4e74-8252-1eca43ee22dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
