<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_OK_paymentCenter</name>
   <tag></tag>
   <elementGuidId>4a065d3a-c4e2-499e-a6b7-2ab156ff3647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='paymentCenterFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paymentCenterFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d16d1f9f-ff24-45c6-996f-5bb129ea332d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>72010feb-f452-4775-be6d-d5f27818948b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentCenterFrame</value>
      <webElementGuid>6836fd3e-af03-4276-ba78-c7244021614f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentCenter</value>
      <webElementGuid>cfb000ec-67de-472e-90bf-e51ef31acb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://payment.klikindomaret.com/paymentcenter/Payments?src=iframe&amp;pcid=klikindomaret&amp;lat=-6.1482915&amp;long=106.7194873&amp;trxtype=createorder&amp;SCTPCID=65b1103e-5288-463f-8314-ff246ce18af2</value>
      <webElementGuid>4f94adb1-2f1c-4e4f-b885-1cce82ef75cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentCenterFrame&quot;)</value>
      <webElementGuid>f8fd88b9-630d-4f99-9dae-225512c3b6cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='paymentCenterFrame']</value>
      <webElementGuid>7e36dbe3-383d-4878-8f42-2f671d4c1860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupPaymentCenter']/div/div/iframe</value>
      <webElementGuid>324fedaf-302d-4846-a4ff-47caf059ed40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>185112b6-bf21-4941-9be4-5d3ed7412d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'paymentCenterFrame' and @name = 'paymentCenter' and @src = 'https://payment.klikindomaret.com/paymentcenter/Payments?src=iframe&amp;pcid=klikindomaret&amp;lat=-6.1482915&amp;long=106.7194873&amp;trxtype=createorder&amp;SCTPCID=65b1103e-5288-463f-8314-ff246ce18af2']</value>
      <webElementGuid>ba92b0ac-d418-437f-9591-ecae526a5774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
