<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bank BCA (Dicek Otomatis)Hanya menerima_4fa77a</name>
   <tag></tag>
   <elementGuidId>98a64c06-ffa9-4777-ac4f-e30a1c437b1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div[2]/div[4]/div/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.stardust-radio.stardust-radio--checked > div.stardust-radio__content > div.stardust-radio__label > div.checkout-bank-transfer-item__card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a79add8d-247b-4024-9fc4-18c5f864d28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout-bank-transfer-item__card</value>
      <webElementGuid>1616198b-68ed-4b99-b673-28791ca79756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bank BCA (Dicek Otomatis)Hanya menerima dari Bank BCA</value>
      <webElementGuid>d730bceb-b25c-49ed-afb0-8dc07b3f306e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;dYFPlI&quot;]/div[@class=&quot;_8ZMqxt&quot;]/div[@class=&quot;kRed1l&quot;]/div[@class=&quot;HgQ4yt&quot;]/div[1]/div[@class=&quot;checkout-payment-setting__payment-method-options&quot;]/div[@class=&quot;bank-transfer-category&quot;]/div[@class=&quot;bank-transfer-category__body&quot;]/div[@class=&quot;checkout-bank-transfer-item&quot;]/div[@class=&quot;stardust-radio stardust-radio--checked&quot;]/div[@class=&quot;stardust-radio__content&quot;]/div[@class=&quot;stardust-radio__label&quot;]/div[@class=&quot;checkout-bank-transfer-item__card&quot;]</value>
      <webElementGuid>0bba588e-8ed4-4f05-af26-c1c5a3625dca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div[2]/div[4]/div/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>6bedf9a9-467e-4b4b-929b-e07763d9789d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bebas Biaya Penanganan'])[1]/following::div[8]</value>
      <webElementGuid>7028c9eb-5f52-49e3-8a4d-b513b2938d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>7192f0d0-80d3-4d7f-96df-a828b6eb0621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Bank BCA (Dicek Otomatis)Hanya menerima dari Bank BCA' or . = 'Bank BCA (Dicek Otomatis)Hanya menerima dari Bank BCA')]</value>
      <webElementGuid>48380562-dcf5-4529-b72e-d7336cf5a684</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
