<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>d73661a6-a614-47de-96e5-d8f5390ecbb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='true']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f30a04b2-b29a-469e-b827-78e7c62aab37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>19c3ad6f-9d94-48b9-be21-86d104953e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c3d0c55-3fc2-405b-a757-dd8b99fe9833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-cart-wrapper&quot;)/section[@class=&quot;bl-section&quot;]/div[@class=&quot;bl-container&quot;]/div[@class=&quot;bl-flex-container justify-center is-gutter-24&quot;]/div[@class=&quot;bl-flex-item is-col-8&quot;]/div[@class=&quot;p-20  mb-16 bl-card bl-card--outlined&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item is-col-6&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item&quot;]/label[@class=&quot;bl-checkbox qa-bulk-checkbox&quot;]/input[1]</value>
      <webElementGuid>d5d721ef-fb31-4415-bc38-44caf70e1ada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='true']</value>
      <webElementGuid>15f12cd4-a759-4b17-b941-f2996f1072a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-cart-wrapper']/section[2]/div/div/div/div/div/div/div/div/label/input</value>
      <webElementGuid>15b82e85-65bc-4a53-8b26-0e5504044a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b4b5b6bd-ae6a-429b-a862-dab7e919931d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>b978c836-7bda-43a6-8075-f1bc630170a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
