<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>f3e08170-9daa-488d-bfe8-ea09d1c6a1c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cart_drawer_target_id']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.shopee-cart-number-badge</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4983d4a0-038d-40a4-a7c2-3993370f20c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shopee-cart-number-badge</value>
      <webElementGuid>02f92a6f-9c03-4600-bce6-d4910549706b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1926d0be-4d7a-4ec6-8577-eee1627fd49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;XmiBHs&quot;]/div[@class=&quot;theme--ofs&quot;]/header[@class=&quot;shopee-top container-wrapper&quot;]/div[@class=&quot;ofs-header container-wrapper&quot;]/div[@class=&quot;ofs-header__top&quot;]/div[@class=&quot;container ofs-header__top-wrapper&quot;]/div[@class=&quot;ofs-header__right&quot;]/div[@class=&quot;ofs-header__cart-wrapper&quot;]/div[@id=&quot;cart_drawer_target_id&quot;]/div[@class=&quot;stardust-popover__target&quot;]/div[@class=&quot;cart-drawer-container&quot;]/a[@id=&quot;cart_drawer_target_id&quot;]/div[@class=&quot;shopee-cart-number-badge&quot;]</value>
      <webElementGuid>af08f450-b26c-4ecf-b4b1-c3d8d6bab4e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cart_drawer_target_id']/div</value>
      <webElementGuid>b60c4cc3-699e-48dd-bbde-1315e9f90f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='raflyrizky'])[1]/following::div[14]</value>
      <webElementGuid>66d43d3e-59f1-4ceb-b466-94e8dda1f541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/following::div[20]</value>
      <webElementGuid>2a59452d-d3ed-48d6-aac9-c5480d1ded5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru Ditambahkan'])[1]/preceding::div[3]</value>
      <webElementGuid>e61819ed-e1d4-4538-9a1b-99420e3f20c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logitech G603 Lightspeed Mouse Gaming Wireless Bluetooth'])[1]/preceding::div[5]</value>
      <webElementGuid>0e85b437-eff0-4480-a18b-94676c61146d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>c6225a90-93f1-4f14-8534-0d3468274639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/div</value>
      <webElementGuid>dd91375b-526d-4e7a-8770-8cea32f5f0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1' or . = '1')]</value>
      <webElementGuid>9beb2a0d-1af9-442d-998e-1de917bb1250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
