<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Whatsapp</name>
   <tag></tag>
   <elementGuidId>fcf5921b-a314-4247-8dfb-01701d453c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-with-otp-wa']/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.bl-text.bl-text--bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>da547f09-7c10-4e97-9376-652d2af75554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-text bl-text--bold</value>
      <webElementGuid>a555e2d4-3feb-4001-9013-860b17af86ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Whatsapp</value>
      <webElementGuid>15cddf60-5b22-46bc-ad1c-5802562da893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-with-otp-wa&quot;)/div[@class=&quot;bl-flex-item&quot;]/div[1]/p[@class=&quot;bl-text bl-text--bold&quot;]</value>
      <webElementGuid>ee93ceab-491e-4cb4-b7ef-e1246d692d5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-with-otp-wa']/div[2]/div/p</value>
      <webElementGuid>620f034b-f8e0-4c5a-92e1-25ae393315c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/following::p[4]</value>
      <webElementGuid>1ddc5658-053c-4fee-8422-8e54af1c0654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::p[8]</value>
      <webElementGuid>0663f2bf-0563-47eb-ab74-02e9cea158b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*****-****-0136'])[1]/preceding::p[1]</value>
      <webElementGuid>6a00ca25-5959-4bda-95a8-fed95495f4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Whatsapp']/parent::*</value>
      <webElementGuid>09372178-96a0-441a-8485-a4e30dddea73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/p</value>
      <webElementGuid>fa5165c7-b1d6-46e4-b73e-5d80a1087c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Whatsapp' or . = 'Whatsapp')]</value>
      <webElementGuid>bce23a73-ab87-499c-8b57-d5a76a14bdab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
