<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Untuk keamanan akun, mohon verifikasi i_9fbf4a</name>
   <tag></tag>
   <elementGuidId>5376a63f-cbc5-4e00-b6a7-4944598fc56d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._3M9lzn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19737eb4-7f23-4e07-afc9-5c9c55063c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3M9lzn</value>
      <webElementGuid>270d17f5-5053-4e58-9fe3-4c40e5e05fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Untuk keamanan akun, mohon verifikasi identitas kamu dengan salah satu cara di bawah ini.Verifikasi melalui linkQ: Mengapa saya diminta untuk verifikasi akun?A: Keamanan akunmu penting bagi kami. Shopee meminta kamu untuk verifikasi agar tidak ada orang lain, kecuali kamu, yang dapat log in ke akunmu.Q: Apa yang dapat saya lakukan jika tidak bisa verifikasi akun?A: Silakan hubungi Customer Service Shopee untuk bantuan log in ke akunmu.</value>
      <webElementGuid>316511ea-7e3c-41ca-89da-75da4de0b14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;vtexOX&quot;]/div[1]/div[@class=&quot;_3M9lzn&quot;]</value>
      <webElementGuid>9103eaa0-2bc6-46fe-8e3b-4a31b27acaf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div</value>
      <webElementGuid>7ac23272-23e8-4496-b66d-f66d5e4f7919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Butuh bantuan?'])[1]/following::div[2]</value>
      <webElementGuid>cec01270-198c-48cc-a8d8-b90868998979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemeriksaan keamanan'])[1]/following::div[2]</value>
      <webElementGuid>9f700cae-b76d-425b-92de-37268d2bf77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>1cd805df-ee30-4b22-999c-0f4709bb8fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Untuk keamanan akun, mohon verifikasi identitas kamu dengan salah satu cara di bawah ini.Verifikasi melalui linkQ: Mengapa saya diminta untuk verifikasi akun?A: Keamanan akunmu penting bagi kami. Shopee meminta kamu untuk verifikasi agar tidak ada orang lain, kecuali kamu, yang dapat log in ke akunmu.Q: Apa yang dapat saya lakukan jika tidak bisa verifikasi akun?A: Silakan hubungi Customer Service Shopee untuk bantuan log in ke akunmu.' or . = 'Untuk keamanan akun, mohon verifikasi identitas kamu dengan salah satu cara di bawah ini.Verifikasi melalui linkQ: Mengapa saya diminta untuk verifikasi akun?A: Keamanan akunmu penting bagi kami. Shopee meminta kamu untuk verifikasi agar tidak ada orang lain, kecuali kamu, yang dapat log in ke akunmu.Q: Apa yang dapat saya lakukan jika tidak bisa verifikasi akun?A: Silakan hubungi Customer Service Shopee untuk bantuan log in ke akunmu.')]</value>
      <webElementGuid>d19455e1-7aa5-4d19-ac31-46f2ac712755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
