<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Verifikasi gagalKamu terlalu sering mem_995f92</name>
   <tag></tag>
   <elementGuidId>19a0c1f1-e27c-4289-bf1f-9bd1a73db9c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._3M9lzn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df3c2487-97ce-420b-b15e-a210ecd4e0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3M9lzn</value>
      <webElementGuid>34840f36-9d7c-402b-b97a-df01ffa4311e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifikasi gagalKamu terlalu sering meminta link autentikasi. Coba lagi nanti.</value>
      <webElementGuid>9c27eb40-2c2a-49a1-beb7-f61dc02c794d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;vtexOX&quot;]/div[1]/div[@class=&quot;_3M9lzn&quot;]</value>
      <webElementGuid>5c95e3f6-527e-42a2-83f9-a72b014dd2a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div</value>
      <webElementGuid>574ab02e-40f2-4be0-8be6-48c606d7ca77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Butuh bantuan?'])[1]/following::div[2]</value>
      <webElementGuid>95a00580-2dfa-4635-b0c6-220e2e9e510b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi melalui link'])[1]/following::div[2]</value>
      <webElementGuid>88eb10e0-7b1c-4998-908c-b0ae02cd9b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>a6288111-644f-4b56-8d68-460281a07ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Verifikasi gagalKamu terlalu sering meminta link autentikasi. Coba lagi nanti.' or . = 'Verifikasi gagalKamu terlalu sering meminta link autentikasi. Coba lagi nanti.')]</value>
      <webElementGuid>8175039e-f7e5-43fc-96e4-0dec0ce55a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
