<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bayar</name>
   <tag></tag>
   <elementGuidId>51dc7941-772a-48ba-b67c-032ab7f50cdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.in-b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout']/div/div/div/div[5]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e0949bb3-e615-4315-a016-f44f3b7cbb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clstag</name>
      <type>Main</type>
      <value>pageclick|keycount|epi_confirm_submitOrder|0</value>
      <webElementGuid>00702f0c-605b-4a7a-b084-1f706bbdc414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>in-b</value>
      <webElementGuid>2792ae5a-22c4-4ff3-8273-8e4fa1dce052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>b5d5b6fb-492c-44c5-9bbd-107a9007f118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bayar</value>
      <webElementGuid>3dedefbb-2d00-450c-bab1-6e6c83251832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout&quot;)/div[@class=&quot;cart-settlement-root&quot;]/div[@class=&quot;cart-settlement-wrapper cart-settlement-wrapper-fixed&quot;]/div[@class=&quot;cart-settlement cart-settlement-top&quot;]/div[@class=&quot;buy-all&quot;]/div[@class=&quot;buy-all-ctrl&quot;]/a[@class=&quot;in-b&quot;]</value>
      <webElementGuid>4e3b5637-a211-4a1f-8897-887a8287bd07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout']/div/div/div/div[5]/div[2]/a</value>
      <webElementGuid>29ed2137-335a-415d-a46d-2d8a8b3d1583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Bayar')])[2]</value>
      <webElementGuid>7c5e009e-2739-4f83-a2b8-ae5a831e1a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 96,500'])[1]/following::a[1]</value>
      <webElementGuid>af75492b-7340-484f-b860-8c8a550486a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Tagihan:'])[1]/following::a[1]</value>
      <webElementGuid>46afc5d3-fe02-4cc7-9973-00f5de07a561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Pengiriman'])[1]/preceding::a[1]</value>
      <webElementGuid>d4ad43e6-0cd9-433e-a627-bbdf72de7b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bayar']/parent::*</value>
      <webElementGuid>a5a5a5dd-52a2-4740-b700-344c560cb4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[3]</value>
      <webElementGuid>ea24ba3f-80c3-47cb-be9b-ed4f2af89883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/a</value>
      <webElementGuid>aa6a4b51-a4ef-4c03-8d11-a401390ec0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'Bayar' or . = 'Bayar')]</value>
      <webElementGuid>5b6348e4-5ce3-4a27-8629-7b1953e28f2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
