<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lanjutkan</name>
   <tag></tag>
   <elementGuidId>714cef4e-39a4-429e-8cd5-04a040f2e522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-message-ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='confirmDialogPopup']/div[3]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a0943263-4002-4aae-9851-17235f1b532b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clstag</name>
      <type>Main</type>
      <value>pageclick|keycount|epi_cart_confirm_submit_order_ok_2016120713|0</value>
      <webElementGuid>5de0064b-3100-4fe3-a8cb-b3e14c378d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-message-ok</value>
      <webElementGuid>e295684a-af3d-42f8-a09a-4742387f7c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjutkan</value>
      <webElementGuid>f855403d-99d0-43ec-b2a4-b7a27b8fb9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmDialogPopup&quot;)/div[@class=&quot;btn-box f-tac&quot;]/button[@class=&quot;btn-message-ok&quot;]</value>
      <webElementGuid>ce353b58-b89d-456e-b137-d5be82cf9d1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='confirmDialogPopup']/div[3]/button[2]</value>
      <webElementGuid>88cbeb05-cc0e-4a30-80ef-96fedd61d4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[2]/following::button[1]</value>
      <webElementGuid>fb7cf088-a7fe-45c2-ba30-038473bb6353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anda tidak bisa mengubah pesanan setelah melakukan konfirmasi'])[1]/following::button[2]</value>
      <webElementGuid>e7ddb595-0539-4fe3-a842-bd00ff0c3c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali ke troli'])[2]/preceding::button[1]</value>
      <webElementGuid>b8378c2f-c8bb-4817-96b2-bdf0cbbc9347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perlindungan Konsumen'])[1]/preceding::button[1]</value>
      <webElementGuid>a11ff673-8f92-4a0c-b345-01030f8060c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan']/parent::*</value>
      <webElementGuid>7eb41f58-d53b-4066-ab52-7f9983a0bacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>469fa61d-b681-4a9c-ad8c-7eeaf496f36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Lanjutkan' or . = 'Lanjutkan')]</value>
      <webElementGuid>649b358d-2100-436c-b56c-0f3fd4767a7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
