<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Whatsappdikirim ke --1016</name>
   <tag></tag>
   <elementGuidId>540394cf-33c8-427c-abb8-d5fb5430e737</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login-with-otp-wa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-with-otp-wa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2a841e2-fbfa-4d34-80ac-959ced15c27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-flex-container align-items-center card-wrapper</value>
      <webElementGuid>4faf6dec-ec88-4482-9908-3c91ab425cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-with-otp-wa</value>
      <webElementGuid>fd2ec88d-793c-445c-95ee-7b1463f0e1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Whatsappdikirim ke: *****-****-1016</value>
      <webElementGuid>bc1e4270-0bb6-41e5-a8bc-8142eb7d1388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-with-otp-wa&quot;)</value>
      <webElementGuid>063a6df1-d65a-4afe-a642-90c2ab9fcba6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='login-with-otp-wa']</value>
      <webElementGuid>e8b5085a-ef73-4636-a1d9-974a12eda25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TFAJS-1659268646352']/section/div/div[2]/div/div[2]/div/div/div/div[2]/div/div</value>
      <webElementGuid>d9df98e9-f34c-44cc-a3d3-0c7b008a1125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/following::div[23]</value>
      <webElementGuid>66ca8f62-3ff0-463d-8216-a7cce56a1b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::div[29]</value>
      <webElementGuid>ccd27cc4-c837-4db3-8013-c2929a3156e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[14]</value>
      <webElementGuid>30897dc6-eb2e-4738-8de0-479def9939c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div</value>
      <webElementGuid>d24cb512-aa15-4a6e-a875-88352101ca84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'login-with-otp-wa' and (text() = 'Whatsappdikirim ke: *****-****-1016' or . = 'Whatsappdikirim ke: *****-****-1016')]</value>
      <webElementGuid>f6905429-261e-4a3f-9f8a-b75bff5842f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
