<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BCA</name>
   <tag></tag>
   <elementGuidId>23e9745b-956a-48ff-a0ac-efd13d98ff06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bl-dropdown__option__item-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-checkout-container']/fragment-loader/div/div/section/div/div/div[3]/div[2]/div/div/div/div/div/div[2]/ul/li/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd9155e5-6454-4da9-a9ba-cfbfbd7c31b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-dropdown__option__item-wrapper</value>
      <webElementGuid>1b1b86c5-2a2d-4107-b846-5974eeb29e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
              BCA
             </value>
      <webElementGuid>5803cd78-9bc8-4508-8b2e-811245979dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-checkout-container&quot;)/fragment-loader[1]/div[@class=&quot;tuku&quot;]/div[1]/section[1]/div[1]/div[@class=&quot;mb-20 bl-card bl-card--outlined&quot;]/div[3]/div[@class=&quot;bl-payment-category&quot;]/div[@class=&quot;bl-flex-item bl-payment-category__detail ph-20 pb-20&quot;]/div[1]/div[1]/div[@class=&quot;mb-12&quot;]/div[@class=&quot;bl-dropdown bl-payment-type__option bl-dropdown--active&quot;]/div[@class=&quot;bl-dropdown__content&quot;]/ul[@class=&quot;bl-dropdown__option&quot;]/li[@class=&quot;bl-dropdown__option__item&quot;]/div[@class=&quot;bl-dropdown__option__item-wrapper&quot;]</value>
      <webElementGuid>de0da982-5f7b-4705-8a74-c5e4b6fdf6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>281be26e-e3f6-4fd1-9574-1e75ccb11a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-dropdown__option__item-wrapper</value>
      <webElementGuid>8188e45d-d12e-4694-bc7c-465be9910e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
              BCA
             </value>
      <webElementGuid>5c886984-2c5e-4ccd-b642-e06a9a963b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-checkout-container&quot;)/fragment-loader[1]/div[@class=&quot;tuku&quot;]/div[1]/section[1]/div[1]/div[@class=&quot;bl-card bl-card--outlined&quot;]/div[@class=&quot;bl-accordion is-active bl-accordion--no-border&quot;]/div[@class=&quot;bl-accordion__body&quot;]/div[1]/div[3]/div[@class=&quot;bl-payment-category&quot;]/div[@class=&quot;bl-flex-item bl-payment-category__detail ph-20 pb-20&quot;]/div[1]/div[1]/div[@class=&quot;mb-12&quot;]/div[@class=&quot;bl-dropdown bl-payment-type__option bl-dropdown--active&quot;]/div[@class=&quot;bl-dropdown__content bl-dropdown__content--opposite&quot;]/ul[@class=&quot;bl-dropdown__option&quot;]/li[@class=&quot;bl-dropdown__option__item&quot;]/div[@class=&quot;bl-dropdown__option__item-wrapper&quot;]</value>
      <webElementGuid>cb83c701-377e-434d-8dc2-505f81c39bac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-checkout-container']/fragment-loader/div/div/section/div/div/div[3]/div[2]/div/div/div/div/div/div[2]/ul/li/div</value>
      <webElementGuid>8a1c43f2-f94a-460f-b5a0-0e98e2a6985c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran'])[1]/following::div[75]</value>
      <webElementGuid>88d87a32-c68e-41c4-86ec-5a6c570554a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Punya kode voucher?'])[1]/preceding::div[130]</value>
      <webElementGuid>d4f2b3be-25bd-498a-b0db-d6e99910509f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan kode voucher'])[1]/preceding::div[130]</value>
      <webElementGuid>5a3eef21-2542-4eeb-acbf-be14e20dc94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div</value>
      <webElementGuid>ae626036-bccd-4aad-81d7-af5cd3fdf09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
              BCA
             ' or . = ' 
              BCA
             ')]</value>
      <webElementGuid>ecaf90c9-a9e0-4cb2-9ea8-6e2ee3d8eb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-checkout-container']/fragment-loader/div/div/section/div/div[2]/div/div[2]/div/div[3]/div[2]/div/div/div/div/div/div[2]/ul/li/div</value>
      <webElementGuid>a74ba895-66af-4840-b8ae-57a8ff3c1313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terakhir kamu pakai'])[1]/following::div[65]</value>
      <webElementGuid>1f2daa1e-9806-4733-8985-32f977b54a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pembayaran'])[1]/following::div[109]</value>
      <webElementGuid>3f45d28d-9ed5-4b89-9903-d9eea6ec3854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Punya kode voucher?'])[1]/preceding::div[97]</value>
      <webElementGuid>ca735ae6-4687-4117-b1b9-b5f77afa3fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan kode voucher'])[1]/preceding::div[97]</value>
      <webElementGuid>6ba3b6bc-1f2f-41d2-b157-b45d84a9d8f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
