<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Terakhir kamu pakai_payment-category</name>
   <tag></tag>
   <elementGuidId>209b20fb-547e-471a-a337-e19470eeea9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='virtual_account']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#virtual_account</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e64d1046-b82c-4aac-8106-bb0ea8b13547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bbabff12-18cb-4fed-adb9-c16c373833bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment-category</value>
      <webElementGuid>e6b2ea5f-45ee-43ba-8ce7-68d7c9c5f15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>virtual_account</value>
      <webElementGuid>72327c7e-759f-4a27-88e7-c7a67d672484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-radio-button__input</value>
      <webElementGuid>cade5fd8-caaa-4ee4-be87-618261e4d4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>virtual_account</value>
      <webElementGuid>8ee829d9-c6f8-42c7-918c-4c009d035320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-checkout-container&quot;)/fragment-loader[1]/div[@class=&quot;tuku&quot;]/div[1]/section[1]/div[1]/div[@class=&quot;bl-card bl-card--outlined&quot;]/div[@class=&quot;bl-accordion is-active bl-accordion--no-border&quot;]/div[@class=&quot;bl-accordion__body&quot;]/div[1]/div[3]/div[@class=&quot;bl-payment-category&quot;]/label[@class=&quot;bl-payment-category__label&quot;]/div[@class=&quot;bl-flex-container p-20&quot;]/div[@class=&quot;bl-flex-item&quot;]/label[@class=&quot;bl-radio-button&quot;]/input[@id=&quot;virtual_account&quot;]</value>
      <webElementGuid>bfd55171-0905-4ece-a7c6-d7c07e07bae6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='virtual_account']</value>
      <webElementGuid>89e89884-ebb3-4959-80a6-208ac0da6aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-checkout-container']/fragment-loader/div/div/section/div/div[2]/div/div[2]/div/div[3]/div/label/div/div/label/input</value>
      <webElementGuid>60ada3e9-c363-4755-bece-8c3b6d15023e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/label/div/div/label/input</value>
      <webElementGuid>87a32f2c-a950-4d6a-8754-935a79cccdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'payment-category' and @id = 'virtual_account']</value>
      <webElementGuid>9aeb741f-52df-4e9c-a3fb-6e5c2d962326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
