<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Geser untuk melengkapi puzzle_JDJRV-sli_0242af</name>
   <tag></tag>
   <elementGuidId>c1ce62ee-90db-4e6c-856f-93112552d29d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.JDJRV-slide-inner.JDJRV-slide-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='JDJRV-wrap-commonBtn']/div[2]/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>16149bd6-ff5d-46aa-9635-82f6a275c33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>JDJRV-slide-inner JDJRV-slide-btn</value>
      <webElementGuid>3908dc3f-b9e8-4bf7-a2a0-3f521f3f73dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JDJRV-wrap-commonBtn&quot;)/div[@class=&quot;JDJRV-pop-content&quot;]/div[@class=&quot;JDJRV-slide JDJRV-joybuy&quot;]/div[@class=&quot;JDJRV-slide-bg&quot;]/div[@class=&quot;JDJRV-slide-inner JDJRV-slide-btn&quot;]</value>
      <webElementGuid>b334a520-c826-4653-9f71-70ddaae5531c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='JDJRV-wrap-commonBtn']/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>767cc1b5-ddb6-4607-a5c7-a6337ad85713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geser untuk melengkapi puzzle.'])[1]/following::div[6]</value>
      <webElementGuid>75101c48-605e-45f4-871a-4e4c16482121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh'])[1]/following::div[14]</value>
      <webElementGuid>fa6d3081-f8d4-42e9-8246-6b1a7cf983c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>915f34d7-4590-4873-b9bf-59da84f3f984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
