<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lanjutkan</name>
   <tag></tag>
   <elementGuidId>ac1e6eb2-a6be-4ab6-ac53-a4e3f008dfb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verifyEmail > #commonBtn > div.btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='commonBtn']/div)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>95e5a4dd-6a64-4d33-bfaf-e225ed8b3fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>ebb3b175-ba0f-4648-9da0-893cae237d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lanjutkan</value>
      <webElementGuid>85c06cbd-da92-4730-819b-1e6b2d310ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifyEmail&quot;)/div[@id=&quot;commonBtn&quot;]/div[@class=&quot;btn&quot;]</value>
      <webElementGuid>903774a6-cc42-4944-86d6-6771554ce6ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='commonBtn']/div)[2]</value>
      <webElementGuid>df327220-daa3-4a53-a5ee-9f7c93d65cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Ulang(78s)'])[1]/following::div[3]</value>
      <webElementGuid>766a91ca-3235-4eab-9cae-aa982ef9a257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/following::div[6]</value>
      <webElementGuid>ccfbdec8-4978-49c4-8ad7-4ca45290c2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada masalah?'])[1]/preceding::div[1]</value>
      <webElementGuid>e4e5d782-dc3e-459f-945f-81407fcd563d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div</value>
      <webElementGuid>d25b027a-16fb-4194-b985-9bf6b31b9c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Lanjutkan' or . = ' Lanjutkan')]</value>
      <webElementGuid>1c78cd28-1aeb-4330-a204-749386aaeaa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
