<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Masuk</name>
   <tag></tag>
   <elementGuidId>0e65da48-cb66-41f8-aa07-6f5335f2c75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='commonBtn']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>23c66bec-8cb9-4001-8ae7-f0b59ff6502a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>e1af8cb6-91bc-4f1b-923f-fd5cc5ca228a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Masuk</value>
      <webElementGuid>97ccd245-b437-4caa-8a83-eb7ce7359add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;contentarea&quot;]/div[3]/div[@id=&quot;commonBtn&quot;]/div[@class=&quot;btn&quot;]</value>
      <webElementGuid>07fdd788-0fae-4d1f-bedb-c68e6a471ed2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commonBtn']/div</value>
      <webElementGuid>80d1320b-7518-47e3-8a5b-7eefda26f235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password'])[1]/following::div[2]</value>
      <webElementGuid>948d63e7-13f5-45b6-968e-b44b1091496b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMS'])[1]/following::div[11]</value>
      <webElementGuid>2262db06-2b15-4643-9a45-ec71e15328f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim kode'])[1]/preceding::div[4]</value>
      <webElementGuid>ea9dfa19-2b19-4d5a-8e9f-2fe38f58dc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div</value>
      <webElementGuid>62aa9369-90e3-4ad9-87a2-7b94cd5fbcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Masuk' or . = ' Masuk')]</value>
      <webElementGuid>c4d485c6-8c6b-4b3d-a63b-23742d0cc397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
