<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>polyline</name>
   <tag></tag>
   <elementGuidId>df688af8-9423-455d-ac80-815486eee88b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>polyline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>polyline</value>
      <webElementGuid>a3a7502b-f225-40de-b172-946fb772f08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9ed41c74-b15a-4514-ad80-43df9eaeffef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>points</name>
      <type>Main</type>
      <value>2 1.7 5.5 1.7 9.6 18.3 21.2 18.3 24.6 6.1 7 6.1</value>
      <webElementGuid>e3ffab32-c1f8-4b76-8fbd-f0527652dc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>d2a1dd62-d9d0-4bfe-9469-1fedbff2d592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>f7058ee5-eaf6-443f-ac6b-0751c869ef40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-miterlimit</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0fcdefaf-895f-4eca-9017-c419c4cf841b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2.5</value>
      <webElementGuid>defc89b1-6210-4053-897c-4d7045ef6e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;XmiBHs&quot;]/div[@class=&quot;theme--ofs&quot;]/header[@class=&quot;shopee-top container-wrapper&quot;]/div[@class=&quot;ofs-header container-wrapper&quot;]/div[@class=&quot;ofs-header__top&quot;]/div[@class=&quot;container ofs-header__top-wrapper&quot;]/div[@class=&quot;ofs-header__right&quot;]/div[@class=&quot;ofs-header__cart-wrapper&quot;]/div[@id=&quot;cart_drawer_target_id&quot;]/div[@class=&quot;stardust-popover__target&quot;]/div[@class=&quot;cart-drawer-container&quot;]/a[@id=&quot;cart_drawer_target_id&quot;]/svg[@class=&quot;shopee-svg-icon navbar__link-icon icon-shopping-cart-2&quot;]/polyline[1]</value>
      <webElementGuid>891e3319-1228-464b-9843-40d92900d296</webElementGuid>
   </webElementProperties>
</WebElementEntity>
