<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Beli</name>
   <tag></tag>
   <elementGuidId>6340816f-2224-46d0-8b1f-9a00e2c6d1f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;AddToCart('adac3367-8bd8-4627-ba75-17e2d4108b94')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>079ce10c-8d4f-4401-a847-95c888b43013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buyBtn </value>
      <webElementGuid>0509e1f1-2c06-4cf5-8bf1-e8a38e6111c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AddToCart('adac3367-8bd8-4627-ba75-17e2d4108b94')</value>
      <webElementGuid>d78f8a81-3430-4e53-9750-1ba6ccb0549b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beli</value>
      <webElementGuid>b418563b-6bcc-49f3-aeaa-008b29cb4b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-detailInfo&quot;)/div[@class=&quot;produk-info-holder&quot;]/div[@class=&quot;each-section section-qty&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 nopadding  col-xs-12&quot;]/div[@class=&quot;wrp-btn&quot;]/button[@class=&quot;buyBtn&quot;]</value>
      <webElementGuid>355f76e7-f1f7-41ce-9016-7a43d0f3effd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;AddToCart('adac3367-8bd8-4627-ba75-17e2d4108b94')&quot;]</value>
      <webElementGuid>662391ea-cbd3-4a24-90e0-996ad41f314f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-detailInfo']/div/div[3]/div[2]/div[3]/div/button</value>
      <webElementGuid>7804c4b3-39ad-45ee-bc71-d72f84a2a803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/following::button[3]</value>
      <webElementGuid>2e3f2a22-0ee1-49ee-8306-108db78442f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUTIH'])[1]/following::button[3]</value>
      <webElementGuid>c2b1ee6e-7fa1-491e-9ae4-a205ab758370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Wishlist'])[1]/preceding::button[1]</value>
      <webElementGuid>3ab9c767-b8be-4e02-a695-81fe50c10b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Produk'])[1]/preceding::button[1]</value>
      <webElementGuid>97ddd8fe-8708-4447-bea9-6be3c496ed25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beli']/parent::*</value>
      <webElementGuid>8f9f37f1-7464-4d2f-b1b0-bd62461f9854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>e1736aa7-6dc7-491d-9054-4569188643a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Beli' or . = 'Beli')]</value>
      <webElementGuid>0b4f8950-4365-4763-adcd-89483bbeb2e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
