<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>8c2e58e2-0a54-4b42-aa8a-6716f6cab5cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61093978-5096-4321-b933-f21186a9ecb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8a607a83-7446-4b21-819e-1f25bb87699f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e3179b61-6e06-4c24-aa34-571fd254e3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-cart-wrapper&quot;)/section[@class=&quot;bl-section&quot;]/div[@class=&quot;bl-container&quot;]/div[@class=&quot;bl-flex-container justify-center is-gutter-24&quot;]/div[@class=&quot;bl-flex-item is-col-8&quot;]/div[@class=&quot;p-20  mb-16 bl-card bl-card--outlined&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item is-col-6&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item&quot;]/label[@class=&quot;bl-checkbox qa-bulk-checkbox&quot;]/input[1]</value>
      <webElementGuid>3d222e6d-1275-4a58-9f24-1665c8d07539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b491b22a-4ceb-4904-b88c-53889d56d990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>560143a1-fb3d-4f23-961b-b842d10058a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4ef8f1b4-ffb8-4cba-b598-66b6ec12f516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-cart-wrapper&quot;)/section[@class=&quot;bl-section&quot;]/div[@class=&quot;bl-container&quot;]/div[@class=&quot;bl-flex-container justify-center is-gutter-24&quot;]/div[@class=&quot;bl-flex-item is-col-8&quot;]/div[@class=&quot;p-20  mb-16 bl-card bl-card--outlined&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item is-col-6&quot;]/div[@class=&quot;bl-flex-container&quot;]/div[@class=&quot;bl-flex-item&quot;]/label[@class=&quot;bl-checkbox qa-bulk-checkbox&quot;]/input[1]</value>
      <webElementGuid>a10502d1-9366-4f6b-bba8-8bb4e2faf70b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='true']</value>
      <webElementGuid>9643a8cc-71c3-4269-b95c-b4372e17e164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-cart-wrapper']/section[2]/div/div/div/div/div/div/div/div/label/input</value>
      <webElementGuid>ec4b1aa1-4e21-4d87-a5d3-1e6d3695ba2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>2649aa0d-2b41-4ccd-a9db-090fbb1f6aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>e3c482c8-d149-4a55-bb24-280479d6a865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
