<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aksi_stardust-checkbox__box</name>
   <tag></tag>
   <elementGuidId>50a97b25-941a-43b4-b60a-784ced259d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._3HHh5A > label.stardust-checkbox > div.stardust-checkbox__box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div[3]/div/div[3]/div/div/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>275a67bc-50e7-49e9-85e3-9225c6059006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stardust-checkbox__box</value>
      <webElementGuid>4bfee223-294b-4cb4-8779-89cefe8009f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;_2LNMKb&quot;]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;_1nft6V&quot;]/div[@class=&quot;aCSbhb&quot;]/div[@class=&quot;_3ApheT&quot;]/div[@class=&quot;_2zUYwP&quot;]/div[@class=&quot;_3HHh5A&quot;]/label[@class=&quot;stardust-checkbox&quot;]/div[@class=&quot;stardust-checkbox__box&quot;]</value>
      <webElementGuid>d34ad34a-d445-4ee8-9a85-42b51265b2d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div[3]/div/div[3]/div/div/div/label/div</value>
      <webElementGuid>b1976341-5f08-4b6f-a8ef-07e4d6449dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/div/label/div</value>
      <webElementGuid>37817d56-697a-419b-a0cb-d6069382c205</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
