<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bayar Sekarang</name>
   <tag></tag>
   <elementGuidId>a0b91a30-61af-4688-a283-519ff08c755e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-cart-checkout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-cart-checkout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e63461b-a5d0-4937-bf58-506db2894a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blue-btn</value>
      <webElementGuid>0e435c1d-0014-4447-8a3b-852a4361ad89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-cart-checkout</value>
      <webElementGuid>a2cd8acb-d82c-48d3-80e3-cee7a420eec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bayar Sekarang</value>
      <webElementGuid>07616ce2-c37e-4486-8fe9-35198a91e4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteHeader&quot;)/div[@class=&quot;top-header desktop&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;bottom-section&quot;]/div[@class=&quot;rightside inline-block&quot;]/div[@class=&quot;wrp-itemlist&quot;]/div[@class=&quot;inline-block&quot;]/div[@class=&quot;each-dropdown list-cart after-login&quot;]/div[@class=&quot;cart-bottom&quot;]/div[@class=&quot;wrp-btn&quot;]/button[@id=&quot;btn-cart-checkout&quot;]</value>
      <webElementGuid>a22d49a2-1475-4844-88f5-312010824d70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-cart-checkout']</value>
      <webElementGuid>8a542fca-1d3a-4668-95bf-fa1e3ef5ac7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='siteHeader']/div/div/div[2]/div[2]/div/div[2]/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>f730fbef-ae9e-48b1-9ad3-f7644f5df0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 110.000'])[5]/following::button[1]</value>
      <webElementGuid>24c0d9b7-7f4b-4562-bd81-25da0529ae5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Pembayaran :'])[1]/following::button[1]</value>
      <webElementGuid>2ad006a8-d315-42fc-a3cc-7120a0b54b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo i.saku:'])[1]/preceding::button[1]</value>
      <webElementGuid>496a9156-61cf-45db-b737-58f5af99f293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poinku :'])[1]/preceding::button[1]</value>
      <webElementGuid>414ea05e-9411-45e1-93b8-2b086a1bf5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bayar Sekarang']/parent::*</value>
      <webElementGuid>ee06ca27-2dcc-4608-8792-909da83953b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>79ebda83-1cd6-4897-83fb-0bb02bab7804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-cart-checkout' and (text() = 'Bayar Sekarang' or . = 'Bayar Sekarang')]</value>
      <webElementGuid>ae570c44-3790-45b2-a29b-56ef42d7304f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
