<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Beli</name>
   <tag></tag>
   <elementGuidId>39d2c245-e131-49ce-9462-280a9ba3dc8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;AddToCart('1b565cb3-7a29-48c8-91ee-eee9d3944af3')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a47be7ee-b0bd-4d6b-8592-b523377e0b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buyBtn </value>
      <webElementGuid>8f463ced-e47e-4789-b11a-544fc3458971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AddToCart('1b565cb3-7a29-48c8-91ee-eee9d3944af3')</value>
      <webElementGuid>f03df836-d123-4f62-ae42-e115052b56b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beli</value>
      <webElementGuid>fe97eaf0-ddb7-4e5e-873f-0294fed4b5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-detailInfo&quot;)/div[@class=&quot;produk-info-holder&quot;]/div[@class=&quot;each-section section-qty&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 nopadding  col-xs-12&quot;]/div[@class=&quot;wrp-btn&quot;]/button[@class=&quot;buyBtn&quot;]</value>
      <webElementGuid>02bce7b8-45c4-41fd-b7a8-752dff114848</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;AddToCart('1b565cb3-7a29-48c8-91ee-eee9d3944af3')&quot;]</value>
      <webElementGuid>337f39c1-7f09-4c1c-a9b2-9b5a5e73df85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='section-detailInfo']/div/div[3]/div/div[3]/div/button</value>
      <webElementGuid>18c2139d-a246-4aa5-970e-2291e41f917a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/following::button[3]</value>
      <webElementGuid>1ab837c9-220c-4f9f-89b1-d271107f24fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Wishlist'])[1]/preceding::button[1]</value>
      <webElementGuid>7e08294f-3a79-4aa1-ac4c-e137f33453ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Produk'])[1]/preceding::button[1]</value>
      <webElementGuid>6d29923b-10ce-40ad-be9b-475b29ab6549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beli']/parent::*</value>
      <webElementGuid>c23d150b-5629-4939-9845-40082f782ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>ce12c9b8-b0a3-49f7-8b01-71e20726c3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Beli' or . = 'Beli')]</value>
      <webElementGuid>3624acd4-671a-4aee-a81c-f028a62e19c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
