<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Produk Virtual_loading</name>
   <tag></tag>
   <elementGuidId>7216c7f3-d580-48c1-b87a-c886fd312a46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='itemCart']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#itemCart > img.loading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>97884d25-dd5a-4a6c-9d83-209491c75b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Assets/image/header/icon_header_cart.png</value>
      <webElementGuid>e438f348-3123-4f73-b329-53153920486a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading</value>
      <webElementGuid>8e0264f9-42ac-429b-b3d0-72e47aab9a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88f24f26-83db-4782-8512-20d756212392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itemCart&quot;)/img[@class=&quot;loading&quot;]</value>
      <webElementGuid>6e0a4915-fe46-4e73-ae51-ababc07d9e0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='itemCart']/img</value>
      <webElementGuid>77b9e207-3097-4acb-b022-122e3ed3c455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/img</value>
      <webElementGuid>cc3768a3-a6b0-4cef-a08c-4a00750beb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Assets/image/header/icon_header_cart.png']</value>
      <webElementGuid>48ffa95b-9970-46f5-a80f-a1a1c2c89d46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
