<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Terakhir kamu pakai_payment-category</name>
   <tag></tag>
   <elementGuidId>d946109c-2024-4804-99e7-9d3b068f1355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='virtual_account']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#virtual_account</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42b8d116-490e-4048-aa4a-3f226d156647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1d1f13fb-4847-4604-a7ab-a47f29968fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment-category</value>
      <webElementGuid>09ceed50-0fae-4b67-8b58-2c15549ae64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>virtual_account</value>
      <webElementGuid>f716b499-f393-4f03-be26-dede1fc3fc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bl-radio-button__input</value>
      <webElementGuid>1d7659a2-ef51-4a90-945a-5169e575541d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>virtual_account</value>
      <webElementGuid>bb40fd49-d5e1-4229-b9ac-606db74c5856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-checkout-container&quot;)/fragment-loader[1]/div[@class=&quot;tuku&quot;]/div[1]/section[1]/div[1]/div[@class=&quot;bl-card bl-card--outlined&quot;]/div[@class=&quot;bl-accordion is-active bl-accordion--no-border&quot;]/div[@class=&quot;bl-accordion__body&quot;]/div[1]/div[3]/div[@class=&quot;bl-payment-category&quot;]/label[@class=&quot;bl-payment-category__label&quot;]/div[@class=&quot;bl-flex-container p-20&quot;]/div[@class=&quot;bl-flex-item&quot;]/label[@class=&quot;bl-radio-button&quot;]/input[@id=&quot;virtual_account&quot;]</value>
      <webElementGuid>bfc9903a-e779-4085-b1c5-873abe125114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='virtual_account']</value>
      <webElementGuid>36ff8c74-9c9e-410e-a5da-01f621b5e753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-checkout-container']/fragment-loader/div/div/section/div/div[2]/div/div[2]/div/div[3]/div/label/div/div/label/input</value>
      <webElementGuid>974e0945-a2e1-45d4-aef0-2a4e18d1f245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/label/div/div/label/input</value>
      <webElementGuid>44ac91bc-320d-446b-a6c9-242eb9775f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'payment-category' and @id = 'virtual_account']</value>
      <webElementGuid>1761b1ee-0911-4d0e-9e14-06b8996da119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
