<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_checkout</name>
   <tag></tag>
   <elementGuidId>e7267be4-960e-4577-b200-5f544f47ae6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div/div/div[3]/div[2]/div[7]/button[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.kcsswk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f5450c18-c91f-4042-83ca-feba205e4f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kcsswk</value>
      <webElementGuid>5d486edf-ee9d-48be-a5e6-30e0757409a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>checkout</value>
      <webElementGuid>78298ceb-f236-4800-a03b-ec51931cb9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[2]/div[@class=&quot;_2LNMKb&quot;]/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;_2jol0L&quot;]/div[@class=&quot;W2HjBQ zzOmij&quot;]/button[@class=&quot;shopee-button-solid shopee-button-solid--primary&quot;]/span[@class=&quot;kcsswk&quot;]</value>
      <webElementGuid>ba24dcb4-19cb-4c25-95a7-d6d600901fe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div/div/div[3]/div[2]/div[7]/button[4]/span</value>
      <webElementGuid>d6b139b0-46b5-4a53-9e10-263f49027c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp361RB'])[1]/following::span[1]</value>
      <webElementGuid>b272d559-bff2-4bdd-8faf-900051546568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kamu mungkin juga suka'])[1]/preceding::span[1]</value>
      <webElementGuid>c2b35a44-af18-48ed-a0cb-62a33527013a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='checkout']/parent::*</value>
      <webElementGuid>07d09202-bdf3-4067-89f7-740c6192b04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/span</value>
      <webElementGuid>7fd1f517-cc81-40a8-844c-f61679150d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'checkout' or . = 'checkout')]</value>
      <webElementGuid>a449bdd2-66ba-4b63-8fff-4fdd08752bc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
