<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bebas Biaya Penanganan_stardust-radio-b_45b9fb</name>
   <tag></tag>
   <elementGuidId>f4f828ef-ff9a-4c07-81ab-a96653e1e446</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.stardust-radio-button.stardust-radio-button--checked > div.stardust-radio-button__outer-circle > div.stardust-radio-button__inner-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div[2]/div[2]/div[4]/div/div/div[2]/div/div[2]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0ca9103-be56-4e67-8233-2619dfd38168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stardust-radio-button__inner-circle</value>
      <webElementGuid>e660f5e5-ace3-4716-b5d2-a3dc9386a013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[1]/div[@class=&quot;dYFPlI&quot;]/div[@class=&quot;_8ZMqxt&quot;]/div[@class=&quot;kRed1l&quot;]/div[@class=&quot;HgQ4yt&quot;]/div[1]/div[@class=&quot;checkout-payment-setting__payment-method-options&quot;]/div[@class=&quot;bank-transfer-category&quot;]/div[@class=&quot;bank-transfer-category__body&quot;]/div[@class=&quot;checkout-bank-transfer-item&quot;]/div[@class=&quot;stardust-radio stardust-radio--checked&quot;]/div[@class=&quot;stardust-radio-button stardust-radio-button--checked&quot;]/div[@class=&quot;stardust-radio-button__outer-circle&quot;]/div[@class=&quot;stardust-radio-button__inner-circle&quot;]</value>
      <webElementGuid>0332d9e7-39e3-41e7-b6de-0745a267095d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div[2]/div[2]/div[4]/div/div/div[2]/div/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>da99787a-b74c-4087-b978-83f588564215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>bae253df-2108-49a9-ae40-0ba7591aa37d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
